//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Captures()
        {
            this.Images = new HashSet<Images>();
        }
    
        public System.Guid ID_Capture { get; set; }
        public Nullable<System.Guid> ID_CaptureType { get; set; }
        public string ID_StatusDetail { get; set; }
        public System.Guid ID_Incident { get; set; }
        public string Comments { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string NamesOfImages { get; set; }
        public string Tokens { get; set; }
    
        public virtual Incidents Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
