//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capture_Type
    {
        public System.Guid ID_CaptureType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CapturesNames { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
