//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public System.Guid ID_Image { get; set; }
        public Nullable<System.Guid> ID_Capture { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.Guid> ID_StatusDetail { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string FileType { get; set; }
    
        public virtual Captures Captures { get; set; }
    }
}
