//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjuredPersons
    {
        public System.Guid ID_InjuredPerson { get; set; }
        public string FullName { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string Phone { get; set; }
        public System.Guid ID_Incident { get; set; }
        public string Age { get; set; }
        public Nullable<bool> IsDriver { get; set; }
        public Nullable<bool> IsPassenger { get; set; }
        public string DriverLicense { get; set; }
        public Nullable<bool> PrivatePerson { get; set; }
        public Nullable<bool> Injured { get; set; }
        public string Hospital { get; set; }
        public string Comments { get; set; }
    
        public virtual Incidents Incidents { get; set; }
    }
}
