//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIREMEntities1 : DbContext
    {
        public SIREMEntities1()
            : base("name=SIREMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Captures> Captures { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Incidents> Incidents { get; set; }
        public virtual DbSet<InjuredPersons> InjuredPersons { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<MailCategories> MailCategories { get; set; }
        public virtual DbSet<Reasons> Reasons { get; set; }
    }
}
