//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capture
    {
        public System.Guid ID_Capture { get; set; }
        public System.Guid ID_Incident { get; set; }
        public System.Guid ID_CaptureType { get; set; }
        public System.Guid ID_StatusDetail { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public string Comments { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Status { get; set; }
    }
}
