//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capture
    {
        public System.Guid ID_Capture { get; set; }
        public System.Guid ID_Incident { get; set; }
        public System.Guid ID_CaptureType { get; set; }
        public System.Guid ID_Status_Detail { get; set; }
        public Nullable<System.DateTime> capture_date { get; set; }
        public string comments { get; set; }
        public System.Guid createdBy { get; set; }
        public System.Guid updatedBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public bool status { get; set; }
    }
}
