//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public System.Guid ID_Cargo { get; set; }
        public string Type { get; set; }
        public string Comments { get; set; }
    }
}
