//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public System.Guid ID_Driver { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string License { get; set; }
        public bool status { get; set; }
        public string Expidation_State { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public string phone_number { get; set; }
    }
}
