//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.Captures = new HashSet<Capture>();
            this.InjuredPersons = new HashSet<InjuredPerson>();
            this.Logs = new HashSet<Log>();
        }
    
        public System.Guid ID_Incident { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public Nullable<System.DateTime> IncidentCloseDate { get; set; }
        public bool PoliceReport { get; set; }
        public string CitationReportNumber { get; set; }
        public string ManifestNumber { get; set; }
        public string LocationReferences { get; set; }
        public string IncidentLatitude { get; set; }
        public string IncidentLongitude { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string ID_Truck { get; set; }
        public string TruckDamage { get; set; }
        public bool TruckCanMove { get; set; }
        public bool TruckNeedCrane { get; set; }
        public string ID_Trailer { get; set; }
        public string TrailerDamage { get; set; }
        public bool TrailerCanMove { get; set; }
        public bool TrailerNeedCrane { get; set; }
        public bool Status { get; set; }
        public string ID_Driver { get; set; }
        public string ID_City { get; set; }
        public string ID_State { get; set; }
        public string ID_Broker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capture> Captures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuredPerson> InjuredPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
