//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident_Report()
        {
            this.Status_Detail = new HashSet<Status_Detail>();
        }
    
        public System.Guid ID_Incident { get; set; }
        public Nullable<System.Guid> ID_Driver { get; set; }
        public Nullable<System.Guid> ID_Location { get; set; }
        public Nullable<System.Guid> ID_CargoType { get; set; }
        public Nullable<System.Guid> ID_StatusDetail { get; set; }
        public string Incident_No { get; set; }
        public Nullable<System.DateTime> Incident_Date { get; set; }
        public Nullable<System.DateTime> Incident_CloseDate { get; set; }
        public string PoliceReport_No { get; set; }
        public Nullable<bool> PoliceReport_Bolean { get; set; }
        public string CitationReport_No { get; set; }
        public Nullable<bool> Injuries { get; set; }
        public string Name_Injuried { get; set; }
        public string Truck_No { get; set; }
        public string Trailer_No { get; set; }
        public Nullable<bool> Truck_Damage { get; set; }
        public Nullable<bool> Trailer_Damage { get; set; }
        public Nullable<bool> CargoSplill { get; set; }
        public string Manifest_No { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_Detail> Status_Detail { get; set; }
    }
}
