//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReport
    {
        public System.Guid ID_Incident { get; set; }
        public System.Guid ID_Driver { get; set; }
        public System.Guid ID_City { get; set; }
        public System.Guid ID_Highway { get; set; }
        public System.Guid ID_Broker { get; set; }
        public Nullable<System.Guid> ID_Capture { get; set; }
        public string ID_StatusDetail { get; set; }
        public string IncidentNo { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public Nullable<System.DateTime> IncidentCloseDate { get; set; }
        public bool PoliceReportBoolean { get; set; }
        public string CitationReportNo { get; set; }
        public bool InjuriesBoolean { get; set; }
        public string InjuredNames { get; set; }
        public string CargoType { get; set; }
        public bool CargoSpill { get; set; }
        public string TruckNo { get; set; }
        public bool TruckDamage { get; set; }
        public bool TruckCanMove { get; set; }
        public bool TruckNeedCrane { get; set; }
        public string TrailerNo { get; set; }
        public bool TrailerDamage { get; set; }
        public bool TrailerCanMove { get; set; }
        public bool TrailerNeedCrane { get; set; }
        public string ManifestNo { get; set; }
        public string LocationReferences { get; set; }
        public string IncidentLatitude { get; set; }
        public string IncidentLongitude { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Status { get; set; }
    }
}
