//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Report
    {
        public System.Guid ID_Incident { get; set; }
        public System.Guid ID_Driver { get; set; }
        public System.Guid ID_Location { get; set; }
        public string ID_Cargo_Type { get; set; }
        public string ID_Status_Detail { get; set; }
        public Nullable<System.Guid> ID_Capture { get; set; }
        public string ID_Status { get; set; }
        public string Incident_No { get; set; }
        public System.DateTime Incident_Date { get; set; }
        public Nullable<System.DateTime> Incident_CloseDate { get; set; }
        public string PoliceReport_No { get; set; }
        public bool PoliceReport { get; set; }
        public string CitationReport_No { get; set; }
        public bool Injuries { get; set; }
        public string Name_Injured { get; set; }
        public string Truck_No { get; set; }
        public bool Truck_Damage { get; set; }
        public string Trailer_No { get; set; }
        public bool Trailer_Damage { get; set; }
        public bool Cargo_Spill { get; set; }
        public string Manifest_No { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Status { get; set; }
    }
}
