//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public System.Guid ID_Journal { get; set; }
        public System.Guid ID_Record { get; set; }
        public System.Guid ID_User { get; set; }
        public string Value { get; set; }
        public string Old_Value { get; set; }
        public string Change { get; set; }
        public string Comments { get; set; }
    }
}
