//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid ID_Log { get; set; }
        public string Description { get; set; }
        public string Change { get; set; }
        public string Value { get; set; }
        public string NewValue { get; set; }
        public System.Guid ID_Incident { get; set; }
        public bool Status { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual Incident Incident { get; set; }
    }
}
