//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseEmergencySystem.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIREMLocalEntities : DbContext
    {
        public SIREMLocalEntities()
            : base("name=SIREMLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<List_Status_Detail_Result> List_Status_Detail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Status_Detail_Result>("List_Status_Detail");
        }
    
        public virtual ObjectResult<List_Incidents_Result> List_Incidents(string iD_Incident, string incident_No, string iD_Driver, string iD_Status_Detail, string truck_No, string trailer_No)
        {
            var iD_IncidentParameter = iD_Incident != null ?
                new ObjectParameter("ID_Incident", iD_Incident) :
                new ObjectParameter("ID_Incident", typeof(string));
    
            var incident_NoParameter = incident_No != null ?
                new ObjectParameter("Incident_No", incident_No) :
                new ObjectParameter("Incident_No", typeof(string));
    
            var iD_DriverParameter = iD_Driver != null ?
                new ObjectParameter("ID_Driver", iD_Driver) :
                new ObjectParameter("ID_Driver", typeof(string));
    
            var iD_Status_DetailParameter = iD_Status_Detail != null ?
                new ObjectParameter("ID_Status_Detail", iD_Status_Detail) :
                new ObjectParameter("ID_Status_Detail", typeof(string));
    
            var truck_NoParameter = truck_No != null ?
                new ObjectParameter("Truck_No", truck_No) :
                new ObjectParameter("Truck_No", typeof(string));
    
            var trailer_NoParameter = trailer_No != null ?
                new ObjectParameter("Trailer_No", trailer_No) :
                new ObjectParameter("Trailer_No", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Incidents_Result>("List_Incidents", iD_IncidentParameter, incident_NoParameter, iD_DriverParameter, iD_Status_DetailParameter, truck_NoParameter, trailer_NoParameter);
        }
    
        public virtual ObjectResult<Update_Incident_Result> Update_Incident(Nullable<System.Guid> iD_Incident, Nullable<System.Guid> iD_Driver, Nullable<System.Guid> iD_Location, Nullable<System.Guid> iD_CargoType, Nullable<System.Guid> iD_StatusDetail, string incident_No, Nullable<System.DateTime> incident_Date, Nullable<System.DateTime> incident_CloseDate, string policeReport_No, Nullable<bool> policeReport_Bolean, string citationReport_No, Nullable<bool> injuries, string name_Injuried, string truck_No, string trailer_No, Nullable<bool> truck_Damage, Nullable<bool> trailer_Damage, Nullable<bool> cargoSplill, string manifest_No, Nullable<System.Guid> iD_User, Nullable<bool> status)
        {
            var iD_IncidentParameter = iD_Incident.HasValue ?
                new ObjectParameter("ID_Incident", iD_Incident) :
                new ObjectParameter("ID_Incident", typeof(System.Guid));
    
            var iD_DriverParameter = iD_Driver.HasValue ?
                new ObjectParameter("ID_Driver", iD_Driver) :
                new ObjectParameter("ID_Driver", typeof(System.Guid));
    
            var iD_LocationParameter = iD_Location.HasValue ?
                new ObjectParameter("ID_Location", iD_Location) :
                new ObjectParameter("ID_Location", typeof(System.Guid));
    
            var iD_CargoTypeParameter = iD_CargoType.HasValue ?
                new ObjectParameter("ID_CargoType", iD_CargoType) :
                new ObjectParameter("ID_CargoType", typeof(System.Guid));
    
            var iD_StatusDetailParameter = iD_StatusDetail.HasValue ?
                new ObjectParameter("ID_StatusDetail", iD_StatusDetail) :
                new ObjectParameter("ID_StatusDetail", typeof(System.Guid));
    
            var incident_NoParameter = incident_No != null ?
                new ObjectParameter("Incident_No", incident_No) :
                new ObjectParameter("Incident_No", typeof(string));
    
            var incident_DateParameter = incident_Date.HasValue ?
                new ObjectParameter("Incident_Date", incident_Date) :
                new ObjectParameter("Incident_Date", typeof(System.DateTime));
    
            var incident_CloseDateParameter = incident_CloseDate.HasValue ?
                new ObjectParameter("Incident_CloseDate", incident_CloseDate) :
                new ObjectParameter("Incident_CloseDate", typeof(System.DateTime));
    
            var policeReport_NoParameter = policeReport_No != null ?
                new ObjectParameter("PoliceReport_No", policeReport_No) :
                new ObjectParameter("PoliceReport_No", typeof(string));
    
            var policeReport_BoleanParameter = policeReport_Bolean.HasValue ?
                new ObjectParameter("PoliceReport_Bolean", policeReport_Bolean) :
                new ObjectParameter("PoliceReport_Bolean", typeof(bool));
    
            var citationReport_NoParameter = citationReport_No != null ?
                new ObjectParameter("CitationReport_No", citationReport_No) :
                new ObjectParameter("CitationReport_No", typeof(string));
    
            var injuriesParameter = injuries.HasValue ?
                new ObjectParameter("Injuries", injuries) :
                new ObjectParameter("Injuries", typeof(bool));
    
            var name_InjuriedParameter = name_Injuried != null ?
                new ObjectParameter("Name_Injuried", name_Injuried) :
                new ObjectParameter("Name_Injuried", typeof(string));
    
            var truck_NoParameter = truck_No != null ?
                new ObjectParameter("Truck_No", truck_No) :
                new ObjectParameter("Truck_No", typeof(string));
    
            var trailer_NoParameter = trailer_No != null ?
                new ObjectParameter("Trailer_No", trailer_No) :
                new ObjectParameter("Trailer_No", typeof(string));
    
            var truck_DamageParameter = truck_Damage.HasValue ?
                new ObjectParameter("Truck_Damage", truck_Damage) :
                new ObjectParameter("Truck_Damage", typeof(bool));
    
            var trailer_DamageParameter = trailer_Damage.HasValue ?
                new ObjectParameter("Trailer_Damage", trailer_Damage) :
                new ObjectParameter("Trailer_Damage", typeof(bool));
    
            var cargoSplillParameter = cargoSplill.HasValue ?
                new ObjectParameter("CargoSplill", cargoSplill) :
                new ObjectParameter("CargoSplill", typeof(bool));
    
            var manifest_NoParameter = manifest_No != null ?
                new ObjectParameter("Manifest_No", manifest_No) :
                new ObjectParameter("Manifest_No", typeof(string));
    
            var iD_UserParameter = iD_User.HasValue ?
                new ObjectParameter("ID_User", iD_User) :
                new ObjectParameter("ID_User", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Incident_Result>("Update_Incident", iD_IncidentParameter, iD_DriverParameter, iD_LocationParameter, iD_CargoTypeParameter, iD_StatusDetailParameter, incident_NoParameter, incident_DateParameter, incident_CloseDateParameter, policeReport_NoParameter, policeReport_BoleanParameter, citationReport_NoParameter, injuriesParameter, name_InjuriedParameter, truck_NoParameter, trailer_NoParameter, truck_DamageParameter, trailer_DamageParameter, cargoSplillParameter, manifest_NoParameter, iD_UserParameter, statusParameter);
        }
    
        public virtual ObjectResult<Update_Status_Detail_Result> Update_Status_Detail(Nullable<System.Guid> iD_Status_Detail, string name)
        {
            var iD_Status_DetailParameter = iD_Status_Detail.HasValue ?
                new ObjectParameter("ID_Status_Detail", iD_Status_Detail) :
                new ObjectParameter("ID_Status_Detail", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Status_Detail_Result>("Update_Status_Detail", iD_Status_DetailParameter, nameParameter);
        }
    
        public virtual ObjectResult<List_Cities_Result> List_Cities(Nullable<System.Guid> iD_State, string state_Name)
        {
            var iD_StateParameter = iD_State.HasValue ?
                new ObjectParameter("ID_State", iD_State) :
                new ObjectParameter("ID_State", typeof(System.Guid));
    
            var state_NameParameter = state_Name != null ?
                new ObjectParameter("State_Name", state_Name) :
                new ObjectParameter("State_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Cities_Result>("List_Cities", iD_StateParameter, state_NameParameter);
        }
    
        public virtual ObjectResult<List_States_Result> List_States(Nullable<System.Guid> iD_State)
        {
            var iD_StateParameter = iD_State.HasValue ?
                new ObjectParameter("ID_State", iD_State) :
                new ObjectParameter("ID_State", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_States_Result>("List_States", iD_StateParameter);
        }
    
        public virtual ObjectResult<Update_Location_Result> Update_Location(Nullable<System.Guid> iD_Location, Nullable<System.Guid> iD_City, Nullable<System.Guid> iD_State, string highway, string latitude, string longitude, string references)
        {
            var iD_LocationParameter = iD_Location.HasValue ?
                new ObjectParameter("ID_Location", iD_Location) :
                new ObjectParameter("ID_Location", typeof(System.Guid));
    
            var iD_CityParameter = iD_City.HasValue ?
                new ObjectParameter("ID_City", iD_City) :
                new ObjectParameter("ID_City", typeof(System.Guid));
    
            var iD_StateParameter = iD_State.HasValue ?
                new ObjectParameter("ID_State", iD_State) :
                new ObjectParameter("ID_State", typeof(System.Guid));
    
            var highwayParameter = highway != null ?
                new ObjectParameter("Highway", highway) :
                new ObjectParameter("Highway", typeof(string));
    
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var referencesParameter = references != null ?
                new ObjectParameter("References", references) :
                new ObjectParameter("References", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Location_Result>("Update_Location", iD_LocationParameter, iD_CityParameter, iD_StateParameter, highwayParameter, latitudeParameter, longitudeParameter, referencesParameter);
        }
    
        public virtual ObjectResult<Update_Driver_Result> Update_Driver(Nullable<System.Guid> iD_Driver, string driver_Name, string driver_Address, string driver_License, string expidation_State, Nullable<System.DateTime> expiration_Date, string phone_Number, Nullable<bool> status)
        {
            var iD_DriverParameter = iD_Driver.HasValue ?
                new ObjectParameter("ID_Driver", iD_Driver) :
                new ObjectParameter("ID_Driver", typeof(System.Guid));
    
            var driver_NameParameter = driver_Name != null ?
                new ObjectParameter("Driver_Name", driver_Name) :
                new ObjectParameter("Driver_Name", typeof(string));
    
            var driver_AddressParameter = driver_Address != null ?
                new ObjectParameter("Driver_Address", driver_Address) :
                new ObjectParameter("Driver_Address", typeof(string));
    
            var driver_LicenseParameter = driver_License != null ?
                new ObjectParameter("Driver_License", driver_License) :
                new ObjectParameter("Driver_License", typeof(string));
    
            var expidation_StateParameter = expidation_State != null ?
                new ObjectParameter("Expidation_State", expidation_State) :
                new ObjectParameter("Expidation_State", typeof(string));
    
            var expiration_DateParameter = expiration_Date.HasValue ?
                new ObjectParameter("Expiration_Date", expiration_Date) :
                new ObjectParameter("Expiration_Date", typeof(System.DateTime));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Driver_Result>("Update_Driver", iD_DriverParameter, driver_NameParameter, driver_AddressParameter, driver_LicenseParameter, expidation_StateParameter, expiration_DateParameter, phone_NumberParameter, statusParameter);
        }
    
        public virtual ObjectResult<Get_Driver_Result> Get_Driver(string license, string phone_Number, string name)
        {
            var licenseParameter = license != null ?
                new ObjectParameter("License", license) :
                new ObjectParameter("License", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Driver_Result>("Get_Driver", licenseParameter, phone_NumberParameter, nameParameter);
        }
    
        public virtual ObjectResult<Update_Cargo_Result> Update_Cargo(Nullable<System.Guid> iD_cargo, string cargo_Type, string comments)
        {
            var iD_cargoParameter = iD_cargo.HasValue ?
                new ObjectParameter("ID_cargo", iD_cargo) :
                new ObjectParameter("ID_cargo", typeof(System.Guid));
    
            var cargo_TypeParameter = cargo_Type != null ?
                new ObjectParameter("Cargo_Type", cargo_Type) :
                new ObjectParameter("Cargo_Type", typeof(string));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Cargo_Result>("Update_Cargo", iD_cargoParameter, cargo_TypeParameter, commentsParameter);
        }
    
        public virtual ObjectResult<Update_Vehicle_Status_Result> Update_Vehicle_Status(Nullable<System.Guid> iD_Status, Nullable<bool> can_Move, Nullable<bool> need_Crane, string comments)
        {
            var iD_StatusParameter = iD_Status.HasValue ?
                new ObjectParameter("ID_Status", iD_Status) :
                new ObjectParameter("ID_Status", typeof(System.Guid));
    
            var can_MoveParameter = can_Move.HasValue ?
                new ObjectParameter("Can_Move", can_Move) :
                new ObjectParameter("Can_Move", typeof(bool));
    
            var need_CraneParameter = need_Crane.HasValue ?
                new ObjectParameter("Need_Crane", need_Crane) :
                new ObjectParameter("Need_Crane", typeof(bool));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Update_Vehicle_Status_Result>("Update_Vehicle_Status", iD_StatusParameter, can_MoveParameter, need_CraneParameter, commentsParameter);
        }
    }
}
